/** Genre options with category subheadings, in display order. */
export const GENRE_GROUPS: { heading: string; genres: string[] }[] = [
  {
    heading: "DANCE / ELECTRONIC",
    genres: [
      "Afro House",
      "Bass",
      "Bass House",
      "Breaks",
      "Chill Out",
      "Deep House",
      "Drum & Bass",
      "Dubstep",
      "Electro House",
      "Electronica",
      "Future House",
      "Glitch Hop",
      "Hard Dance",
      "Hardcore / Hard Techno",
      "House",
      "Indie Dance / Nu Disco",
      "Progressive House",
      "Psy Trance",
      "Tech House",
      "Techno",
      "Trance",
      "Trap",
      "Trip-Hop",
    ],
  },
  {
    heading: "HIP-HOP / R&B",
    genres: ["R&B", "Disco", "Funk", "Hip-Hop", "Soul"],
  },
  {
    heading: "POP / ROCK",
    genres: [
      "Acoustic",
      "Alternative",
      "Pop",
      "Country",
      "Folk",
      "Indie",
      "K-Pop",
      "Metal",
      "Punk",
      "Rock",
      "Singer Songwriter",
    ],
  },
  {
    heading: "",
    genres: ["World"],
  },
  {
    heading: "OTHER",
    genres: [
      "Blues",
      "Christian",
      "Classical",
      "Dancehall",
      "Dub",
      "Gospel",
      "Jazz",
      "Latin",
      "Reggae",
      "Reggaeton",
      "Other",
    ],
  },
];
